package ar.com.comunicar.common.candidato;

public enum ExperienciaLaboral {

	AGROPECUARIA, ARQUITECTURA, ATENCION_AL_CLIENTE, COMPRAS, COMUNICACION, CONSTRUCCION, CONTABILIDAD_FINANZAS, DISENIO, DOCENCIA, FOTOGRAFIA, GASTRONOMIA, INFORMATICA, INGENIERIA, INVESTIGACION, LEGALES, LOGISTICA, MANTENIMIENTO_REPARACIONES_TECNICAS, MANUFACTURA, MEDICINA, OFICINA, OPERARIO, PSICOLOGIA, PUBLICIDAD, RRHH, RRPP, SERVICIOS_GENERALES, TALLER_MECANICO, TRANSPORTE, TURISMO, VENTAS, PROMOCIONES, NO_TENGO,
	ASESORAMIENTO_JURIDICO
}
