package ar.com.comunicar.common.candidato;

public enum FormacionAlcanzada {
	PRIMARIO, SECUNDARIO, SECUNDARIO_EN_CURSO, SECUNDARIO_ABANDONADO, TERCIARIO, TERCIARIO_EN_CURSO, TERCIARIO_ABANDONADO, UNIVERSITARIO, UNIVERSITARIO_EN_CURSO, UNIVERSITARIO_ABANDONADO, POSTGRADO
}
