package ar.com.comunicar.common.candidato;

public enum FormacionEn {
	ABOGACIA, ARQUITECTURA, CIENCIAS_POLITICAS, COMUNICACION_SOCIAL_PERIODISMO, DISENIO_GRAFICO, DISENIO_DE_INTERIORES, DOCENCIA, CIENCIAS_ECONOMICAS, FARMACIA, FOTOGRAFIA, GASTRONOMIA, INGENIERIA_ELECTRONICA, INGENIERIA_MECANICA, INGENIERIA_EN_SISTEMAS, INGENIERIA_CIVIL, INGENIERIA_AGRONOMA, MARTILLERO_PUBLICO, MEDICINA_SALUD, PSICOLOGIA_PSICOPEDAGOGIA, PUBLICIDAD, RRHH, HOTELERIA_TURISMO, MARKETING, SEGURIDAD_HIGIENE, TECNICO_ELECTROMECANICO, TECNICO_MECANICO, TECNICO, TRABAJO_SOCIAL, COMUNICACION_MARKETING,
	ADMINISTRACION_EMPRESAS, INGENIERIA_AGRIMENSURA, INGENIERIA_INDUSTRIAL, BIOINGENIERIA, INGENIERIA_QUIMICO, MAESTRO_MAYOR_OBRAS, ADMINISTRATIVO_CONTABLE, COMERCIO_INTERNACIONAL, DISENIO_INDUMENTARIA, GESTION_PYMES, IDIOMA, INSTRUCTOR_GIMNASIO, NUTRICION, PERIODISMO, RELACIONES_PUBLICAS, TECNICO_AGRONOMO, TOPO_CARTOGRAFO ,VISITADOR_MEDICO
}
